version: '3'

services:
  draw_web:
    build: draw_web
    volumes:
      - ../app/:/var/www/html/
    working_dir: /var/www/html
    ports:
      - "8080:80"
  draw_db:
    build: draw_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: draw_db
    ports:
      - "3308:3306"
    volumes:
      - ./draw_db/base:/draw_db
    working_dir: /draw_db


